### ISSUE TITLE
Crash on clicking emergency phone buttons

### ISSUE THREAD

**Issue by yyc1217** [NCU-CC/NCU-MAP#1]
By using a tablet that without phone functionality, It will crash if I clicked emergency phone buttons below at first page.

``` Java
E/AndroidRuntime(12494): FATAL EXCEPTION: main
E/AndroidRuntime(12494): Process: tw.edu.ncu.cc.ncumap, PID: 12494
E/AndroidRuntime(12494): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.DIAL dat=tel:xx-xxxxxxxxxxxxx }
E/AndroidRuntime(12494):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
E/AndroidRuntime(12494):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime(12494):    at android.app.Activity.startActivityForResult(Activity.java:3424)
E/AndroidRuntime(12494):    at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime(12494):    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
E/AndroidRuntime(12494):    at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime(12494):    at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime(12494):    at tw.edu.ncu.cc.ncumap.MyActivity$1.onClick(MyActivity.java:87)
E/AndroidRuntime(12494):    at android.view.View.performClick(View.java:4438)
E/AndroidRuntime(12494):    at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime(12494):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(12494):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12494):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12494):    at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(12494):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12494):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12494):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(12494):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(12494):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(13146):   Force finishing activity tw.edu.ncu.cc.ncumap/.MyActivity
```

**Comment by c910335** [comment]
If the device doesn't have call ability, the emergency call buttons will not show now.
